spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/fag_quality
spring.datasource.username=marcelo
spring.datasource.password=qualidade123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
